import type { Tenant, User, Product, StoreStory, AddonGroup } from "./types";

// =========================================================================
// EXPANSÃO DO CATÁLOGO TOP FOOD: 9 NOVAS LOJAS DEMO (TOTALIZANDO 20 LOJAS)
// Segmentos: Massas/Italiana, Hot Dog, Mexicana, Comida Mineira,
// Pastelaria Crocante, Frango no Balde, Crepes & Tapiocas, Padaria & Cafeteria, Poke & Saudável
// =========================================================================

export const extraTenants: Tenant[] = [
  // 12. Massas & Cozinha Italiana
  {
    id: "tenant-cantina-italiana",
    name: "Cantina & Massas Bella Pasta",
    slug: "cantina-italiana",
    email: "contato@bellapasta.com.br",
    phone: "11981234501",
    whatsapp: "5511981234501",
    motoboyPhone: "5511981234501",
    motoboyName: "Matheus (Entregador)",
    pixKey: "contato@bellapasta.com.br",
    pixKeyType: "email",
    deliveryFee: 6.5,
    deliveryTime: "30-45 min",
    address: "Rua Garibaldi, 450 - Centro",
    hours: "18:30 - 23:30",
    tagline: "Massas frescas artesanais, lasanhas gratinadas no forno e parmegianas clássicas",
    announcement: "🍝 Terça da Parmegiana: Peça um prato grande e ganhe uma porção extra de batatas rústicas!",
    logo: "🍝",
    bannerImage: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#B91C1C",
    secondaryColor: "#1C1917",
    primaryDark: "#991B1B",
    primaryLight: "#EF4444",
    accentColor: "#F59E0B",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 7,
    businessType: "Massas & Cozinha Italiana",
    localidade: "São Francisco (Centro)",
    rating: 4.9,
    ratingCount: 215,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 14 * 86400000,
    updatedAt: Date.now(),
  },

  // 13. Hot Dog & Lanches Rápidos
  {
    id: "tenant-dogao-prensado",
    name: "Dogão Prensado & Lanches Rápidos",
    slug: "dogao-prensado",
    email: "contato@dogaoprensado.com.br",
    phone: "11981234502",
    whatsapp: "5511981234502",
    motoboyPhone: "5511981234502",
    motoboyName: "Lucas Motoboy",
    pixKey: "contato@dogaoprensado.com.br",
    pixKeyType: "email",
    deliveryFee: 4.5,
    deliveryTime: "20-35 min",
    address: "Av. Tiradentes, 320 - Centro",
    hours: "17:30 - 00:30",
    tagline: "O verdadeiro cachorro-quente prensado na chapa com purê caseiro e bacon",
    announcement: "🌭 Combo Dogão Duplo + Refrigerante Lata com desconto imperdível para entrega rápida!",
    logo: "🌭",
    bannerImage: "https://images.unsplash.com/photo-1619740455993-9e612b1af08a?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#EA580C",
    secondaryColor: "#18181B",
    primaryDark: "#C2410C",
    primaryLight: "#FB923C",
    accentColor: "#FBBF24",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 8,
    businessType: "Hot Dog & Lanches Rápidos",
    localidade: "Gargaú",
    rating: 4.8,
    ratingCount: 342,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 12 * 86400000,
    updatedAt: Date.now(),
  },

  // 14. Cozinha Mexicana
  {
    id: "tenant-taco-loco",
    name: "Taco Loco Gastronomia Mexicana",
    slug: "taco-loco",
    email: "hola@tacoloco.com.br",
    phone: "11981234503",
    whatsapp: "5511981234503",
    motoboyPhone: "5511981234503",
    motoboyName: "Fernando Entregador",
    pixKey: "hola@tacoloco.com.br",
    pixKeyType: "email",
    deliveryFee: 6.0,
    deliveryTime: "30-45 min",
    address: "Rua México, 110 - Jardins",
    hours: "18:00 - 23:45",
    tagline: "Tacos crocantes, burritos artesanais bem recheados, quesadillas e guacamole fresca",
    announcement: "🌮 Noite Mexicana: Combo Fiesta com 4 Tacos + Nachos Supreme com Sour Cream e Cheddar!",
    logo: "🌮",
    bannerImage: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#059669",
    secondaryColor: "#111827",
    primaryDark: "#047857",
    primaryLight: "#34D399",
    accentColor: "#F59E0B",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 6,
    businessType: "Cozinha Mexicana & Tacos",
    localidade: "São Francisco (Centro)",
    rating: 4.9,
    ratingCount: 198,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 11 * 86400000,
    updatedAt: Date.now(),
  },

  // 15. Comida Mineira & Feijoada
  {
    id: "tenant-fogao-de-minas",
    name: "Fogão de Minas Comida Caseira",
    slug: "fogao-de-minas",
    email: "contato@fogaodeminas.com.br",
    phone: "11981234504",
    whatsapp: "5511981234504",
    motoboyPhone: "5511981234504",
    motoboyName: "Tiago Silva",
    pixKey: "contato@fogaodeminas.com.br",
    pixKeyType: "email",
    deliveryFee: 5.5,
    deliveryTime: "30-45 min",
    address: "Estrada Real, 770 - Tradição",
    hours: "11:00 - 16:00",
    tagline: "A autêntica comida mineira na panela de ferro: feijoada completa, costelinha e torresmo pururuca",
    announcement: "🍲 Feijoada Completa para 2 pessoas com arroz, couve, farofa crocante e torresmo!",
    logo: "🍲",
    bannerImage: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#78350F",
    secondaryColor: "#18181B",
    primaryDark: "#451A03",
    primaryLight: "#B45309",
    accentColor: "#F59E0B",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 7,
    businessType: "Comida Mineira & Feijoada",
    localidade: "Barra do Itabapoana",
    rating: 4.8,
    ratingCount: 260,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 16 * 86400000,
    updatedAt: Date.now(),
  },

  // 16. Pastelaria Especial & Caldo de Cana
  {
    id: "tenant-pastel-ouro",
    name: "Pastel D'Ouro Crocante & Caldo de Cana",
    slug: "pastel-ouro",
    email: "contato@pasteldouro.com.br",
    phone: "11981234505",
    whatsapp: "5511981234505",
    motoboyPhone: "5511981234505",
    motoboyName: "Danilo Motoboy",
    pixKey: "contato@pasteldouro.com.br",
    pixKeyType: "email",
    deliveryFee: 4.0,
    deliveryTime: "20-35 min",
    address: "Rua do Comércio, 195 - Feira",
    hours: "16:00 - 23:30",
    tagline: "Pastéis gigantes de 30cm super recheados, fritos na hora com massa sequinha e caldo de cana puro",
    announcement: "🥟 Ganhe 500ml de Caldo de Cana geladinho ao pedir 2 pastéis especiais da casa!",
    logo: "🥟",
    bannerImage: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#D97706",
    secondaryColor: "#1E293B",
    primaryDark: "#B45309",
    primaryLight: "#FBBF24",
    accentColor: "#EF4444",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 6,
    businessType: "Pastelarias",
    localidade: "Gargaú",
    rating: 4.9,
    ratingCount: 288,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 9 * 86400000,
    updatedAt: Date.now(),
  },

  // 17. Frango Frito & Baldes Crocantes
  {
    id: "tenant-frango-crocante",
    name: "Crispy Chicken - Frango no Balde",
    slug: "frango-crocante",
    email: "pedidos@crispychicken.com.br",
    phone: "11981234506",
    whatsapp: "5511981234506",
    motoboyPhone: "5511981234506",
    motoboyName: "Gabriel Entregas",
    pixKey: "pedidos@crispychicken.com.br",
    pixKeyType: "email",
    deliveryFee: 5.0,
    deliveryTime: "25-40 min",
    address: "Av. Independência, 880 - Centro",
    hours: "18:00 - 23:45",
    tagline: "Baldes de frango frito no estilo americano: crocante por fora, suculento por dentro e com molhos especiais",
    announcement: "🍗 Balde Família com 1kg de tirinhas empanadas + batata frita + 3 molhos à sua escolha!",
    logo: "🍗",
    bannerImage: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#DC2626",
    secondaryColor: "#0F172A",
    primaryDark: "#991B1B",
    primaryLight: "#F87171",
    accentColor: "#F59E0B",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 8,
    businessType: "Frango Frito & Porções",
    localidade: "São Francisco (Centro)",
    rating: 4.8,
    ratingCount: 312,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 8 * 86400000,
    updatedAt: Date.now(),
  },

  // 18. Creperia & Tapiocas Gourmet
  {
    id: "tenant-crepe-paris",
    name: "Creperia & Tapiocaria Paris",
    slug: "crepe-paris",
    email: "bonjour@creperiaparis.com.br",
    phone: "11981234507",
    whatsapp: "5511981234507",
    motoboyPhone: "5511981234507",
    motoboyName: "André Express",
    pixKey: "bonjour@creperiaparis.com.br",
    pixKeyType: "email",
    deliveryFee: 4.5,
    deliveryTime: "20-35 min",
    address: "Rua das Flores, 210 - Riviera",
    hours: "16:00 - 23:00",
    tagline: "Crepes franceses finos, tapiocas recheadas na hora, panquecas americanas e waffles com morango",
    announcement: "🥞 Crepe de Nutella com Morangos Frescos e Sorvete de Creme com entrega super rápida!",
    logo: "🥞",
    bannerImage: "https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#BE185D",
    secondaryColor: "#1E1B4B",
    primaryDark: "#831843",
    primaryLight: "#F472B6",
    accentColor: "#FBBF24",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 5,
    businessType: "Crepes, Panquecas & Tapiocas",
    localidade: "Barra do Itabapoana",
    rating: 4.9,
    ratingCount: 165,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 6 * 86400000,
    updatedAt: Date.now(),
  },

  // 19. Padaria & Empório Pão Dourado
  {
    id: "tenant-padaria-pao-dourado",
    name: "Padaria & Empório Pão Dourado",
    slug: "padaria-pao-dourado",
    email: "pedidos@paodourado.com.br",
    phone: "11981234508",
    whatsapp: "5511981234508",
    motoboyPhone: "5511981234508",
    motoboyName: "Marcelo Entregador",
    pixKey: "pedidos@paodourado.com.br",
    pixKeyType: "email",
    deliveryFee: 4.0,
    deliveryTime: "20-35 min",
    address: "Av. Central, 550 - Bairro Nobre",
    hours: "06:30 - 21:30",
    tagline: "Pães de fermentação natural, croissants folhados amanteigados, lanches no pão francês e cafés especiais",
    announcement: "🥖 Café da Tarde: Croissant de Manteiga Recheado + Café Gelado Especial com chantilly!",
    logo: "🥖",
    bannerImage: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#B45309",
    secondaryColor: "#1C1917",
    primaryDark: "#78350F",
    primaryLight: "#FBBF24",
    accentColor: "#F59E0B",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 9,
    businessType: "Padarias & Cafés",
    localidade: "Gargaú",
    rating: 4.9,
    ratingCount: 420,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 25 * 86400000,
    updatedAt: Date.now(),
  },

  // 20. Aloha Poke & Saladas Saudáveis
  {
    id: "tenant-poke-tropical",
    name: "Aloha Hawaiian Poke & Saladas",
    slug: "poke-tropical",
    email: "aloha@poketropical.com.br",
    phone: "11981234509",
    whatsapp: "5511981234509",
    motoboyPhone: "5511981234509",
    motoboyName: "Renan Silva",
    pixKey: "aloha@poketropical.com.br",
    pixKeyType: "email",
    deliveryFee: 5.0,
    deliveryTime: "25-40 min",
    address: "Rua do Sol, 330 - Orla",
    hours: "11:30 - 22:30",
    tagline: "Pokes havaianos frescos com salmão e atum marinados, bowls fitness, wraps leves e sucos naturais prensados",
    announcement: "🥗 Monte seu Poke Grande com 2 proteínas frescas + 5 acompanhamentos à sua escolha!",
    logo: "🥗",
    bannerImage: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80",
    primaryColor: "#0D9488",
    secondaryColor: "#042F2E",
    primaryDark: "#0F766E",
    primaryLight: "#2DD4BF",
    accentColor: "#F59E0B",
    themeMode: "light",
    menuLayout: "list",
    showFeaturedCarousel: true,
    isFeatured: true,
    priorityOrder: 8,
    businessType: "Poke & Alimentação Saudável",
    localidade: "São Francisco (Centro)",
    rating: 4.9,
    ratingCount: 178,
    status: "active",
    isOpen: true,
    subscriptionStatus: "demo",
    monthlyFee: 49.9,
    createdAt: Date.now() - 7 * 86400000,
    updatedAt: Date.now(),
  },
];

// =========================================================================
// USUÁRIOS ADMIN PARA AS NOVAS LOJAS
// =========================================================================
export const extraUsers: User[] = [
  {
    id: "user-bellapasta",
    email: "contato@bellapasta.com.br",
    password: "admin",
    name: "Chef Giovanni (Bella Pasta)",
    role: "tenant_admin",
    tenantId: "tenant-cantina-italiana",
    status: "active",
    createdAt: Date.now() - 14 * 86400000,
  },
  {
    id: "user-dogaoprensado",
    email: "contato@dogaoprensado.com.br",
    password: "admin",
    name: "Marcos (Dogão Prensado)",
    role: "tenant_admin",
    tenantId: "tenant-dogao-prensado",
    status: "active",
    createdAt: Date.now() - 12 * 86400000,
  },
  {
    id: "user-tacoloco",
    email: "hola@tacoloco.com.br",
    password: "admin",
    name: "Rodrigo (Taco Loco)",
    role: "tenant_admin",
    tenantId: "tenant-taco-loco",
    status: "active",
    createdAt: Date.now() - 11 * 86400000,
  },
  {
    id: "user-fogaodeminas",
    email: "contato@fogaodeminas.com.br",
    password: "admin",
    name: "Dona Neide (Fogão de Minas)",
    role: "tenant_admin",
    tenantId: "tenant-fogao-de-minas",
    status: "active",
    createdAt: Date.now() - 16 * 86400000,
  },
  {
    id: "user-pasteldouro",
    email: "contato@pasteldouro.com.br",
    password: "admin",
    name: "Valter (Pastel D'Ouro)",
    role: "tenant_admin",
    tenantId: "tenant-pastel-ouro",
    status: "active",
    createdAt: Date.now() - 9 * 86400000,
  },
  {
    id: "user-crispychicken",
    email: "pedidos@crispychicken.com.br",
    password: "admin",
    name: "Alexandre (Crispy Chicken)",
    role: "tenant_admin",
    tenantId: "tenant-frango-crocante",
    status: "active",
    createdAt: Date.now() - 8 * 86400000,
  },
  {
    id: "user-crepeparis",
    email: "bonjour@creperiaparis.com.br",
    password: "admin",
    name: "Sophie (Creperia Paris)",
    role: "tenant_admin",
    tenantId: "tenant-crepe-paris",
    status: "active",
    createdAt: Date.now() - 6 * 86400000,
  },
  {
    id: "user-paodourado",
    email: "pedidos@paodourado.com.br",
    password: "admin",
    name: "Mestre Padeiro Moacir",
    role: "tenant_admin",
    tenantId: "tenant-padaria-pao-dourado",
    status: "active",
    createdAt: Date.now() - 25 * 86400000,
  },
  {
    id: "user-poketropical",
    email: "aloha@poketropical.com.br",
    password: "admin",
    name: "Marina (Aloha Poke)",
    role: "tenant_admin",
    tenantId: "tenant-poke-tropical",
    status: "active",
    createdAt: Date.now() - 7 * 86400000,
  },
];

// =========================================================================
// PRODUTOS DAS NOVAS LOJAS (CARDÁPIOS RICOS, FOTOS LINDAS E PREÇOS REAIS)
// =========================================================================
export const extraProducts: Product[] = [
  // 12. Cantina & Massas Bella Pasta (tenant-cantina-italiana)
  {
    id: "prod-bp-1",
    tenantId: "tenant-cantina-italiana",
    name: "Lasanha Bolonhesa Especial da Nona",
    description: "Massa fresca artesanal em camadas generosas com ragù clássico de carnes nobres, queijo muçarela derretido e molho bechamel cremoso, gratinada com parmesão ralado na hora.",
    price: 38.9,
    category: "massas",
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-bp-parmesao", name: "Parmesão Ralado Extra (50g)", price: 4.5 },
      { id: "opt-bp-combo-refri", name: "Adicionar Coca-Cola Lata 350ml", price: 6.0 },
    ],
  },
  {
    id: "prod-bp-2",
    tenantId: "tenant-cantina-italiana",
    name: "Filé Mignon à Parmegiana Clássico",
    description: "Generoso filé mignon empanado crocante coberto com molho artesanal de tomates pelados italianos e gratinado com muçarela farta. Acompanha arroz branco e batatas rústicas douradas.",
    price: 49.9,
    category: "especiais",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
    options: [
      { id: "opt-bp-tamanho-2p", name: "Porção Família (Serve 2 Pessoas)", price: 35.0 },
    ],
  },
  {
    id: "prod-bp-3",
    tenantId: "tenant-cantina-italiana",
    name: "Fettuccine Alfredo com Tiras de Frango Grelhado",
    description: "Massa fettuccine al dente envolvida em molho aveludado de manteiga de primeira, creme de leite fresco e queijo grana padano, finalizada com tiras suculentas de peito de frango temperado.",
    price: 36.5,
    category: "massas",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-bp-4",
    tenantId: "tenant-cantina-italiana",
    name: "Tiramisù Tradicional Italiano",
    description: "Sobremesa clássica com biscoitos savoiardi embebidos em café espresso aromático, creme leve de mascarpone e cacau em pó 100% puro polvilhado no topo.",
    price: 18.0,
    category: "sobremesas",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },

  // 13. Dogão Prensado & Lanches Rápidos (tenant-dogao-prensado)
  {
    id: "prod-dp-1",
    tenantId: "tenant-dogao-prensado",
    name: "Dogão Especial Duplo Prensado na Chapa",
    description: "Pão de hot dog macio prensado na chapa com 2 salsichas Perdigão grelhadas, purê de batata cremoso artesanal, milho verde, ervilha, vinagrete da casa, queijo derretido, maionese temperada e batata palha fininha crocante.",
    price: 21.9,
    category: "hotdogs",
    image: "https://images.unsplash.com/photo-1619740455993-9e612b1af08a?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-dp-catupiry", name: "Adicionar Catupiry Original", price: 3.5 },
      { id: "opt-dp-cheddar-bacon", name: "Cheddar Cremoso + Farofa de Bacon", price: 4.5 },
    ],
  },
  {
    id: "prod-dp-2",
    tenantId: "tenant-dogao-prensado",
    name: "Dogão Tudo & Frango Desfiado",
    description: "O mais recheado da cidade: 2 salsichas, peito de frango desfiado temperadinho, bacon crocante em cubos, purê artesanal de batata, queijo muçarela prensado e batata palha à vontade.",
    price: 26.5,
    category: "hotdogs",
    image: "https://images.unsplash.com/photo-1627054234553-9f89972b9472?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
  },
  {
    id: "prod-dp-3",
    tenantId: "tenant-dogao-prensado",
    name: "Batata Frita Crinkle com Cheddar & Bacon",
    description: "Porção média de batatas em formato ondulado super crocantes por fora e macias por dentro, cobertas com calda cremosa de queijo cheddar e cubinhos de bacon fritos.",
    price: 18.0,
    category: "porcoes",
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-dp-4",
    tenantId: "tenant-dogao-prensado",
    name: "Refrigerante Lata 350ml Geladíssimo",
    description: "Coca-Cola, Guaraná Antarctica ou Fanta Laranja na temperatura ideal para acompanhar o seu dogão.",
    price: 6.0,
    category: "bebidas",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },

  // 14. Taco Loco Gastronomia Mexicana (tenant-taco-loco)
  {
    id: "prod-tl-1",
    tenantId: "tenant-taco-loco",
    name: "Trio de Tacos Crocantes Supreme",
    description: "3 tortilhas de milho crocantes recheadas com carne moída temperada com especiarias mexicanas, alface americana fresca, pico de gallo, queijo cheddar ralado e sour cream suave.",
    price: 34.0,
    category: "tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-tl-pimenta", name: "Pimenta Jalapeño Extra", price: 3.0 },
      { id: "opt-tl-guacamole", name: "Potinho Extra de Guacamole Fresca", price: 6.0 },
    ],
  },
  {
    id: "prod-tl-2",
    tenantId: "tenant-taco-loco",
    name: "Burrito Gigante Barbacoa",
    description: "Grande tortilha macia de trigo tostada na chapa, recheada com carne bovina desfiada marinada lentamente, arroz mexicano, feijão preto refrito, queijo derretido e molho salsa da casa.",
    price: 36.9,
    category: "burritos",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
  },
  {
    id: "prod-tl-3",
    tenantId: "tenant-taco-loco",
    name: "Nachos Supreme com Queijo Cheddar & Guacamole",
    description: "Porção generosa de totopos de milho crocantes artesanais, acompanhados de guacamole fresca com limão e coentro, molho cheddar cremoso aquecido e sour cream.",
    price: 28.5,
    category: "nachos",
    image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-tl-4",
    tenantId: "tenant-taco-loco",
    name: "Churros Mexicanos com Doce de Leite & Canela",
    description: "4 unidades de churros sequinhos e dourados passados no açúcar e canela, servidos com pote caprichado de doce de leite cremoso artesanal.",
    price: 16.0,
    category: "sobremesas",
    image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },

  // 15. Fogão de Minas Comida Caseira (tenant-fogao-de-minas)
  {
    id: "prod-fm-1",
    tenantId: "tenant-fogao-de-minas",
    name: "Feijoada Completa Tradicional (Serve 2)",
    description: "Feijoada encorpada cozida lentamente com carnes nobres selecionadas (carne seca, lombo, costelinha suína, paio e calabresa). Acompanha arroz soltinho, couve mineira fininha refogada no alho, farofa de milho crocante com bacon e torresmo à pururuca.",
    price: 54.9,
    category: "pratos-principais",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-fm-molho-pimenta", name: "Molho de Pimenta da Casa (Grátis)", price: 0.0 },
      { id: "opt-fm-extra-torresmo", name: "Porção Extra de Torresmo Pururuca (150g)", price: 8.0 },
    ],
  },
  {
    id: "prod-fm-2",
    tenantId: "tenant-fogao-de-minas",
    name: "Costelinha Mineira com Tutu de Feijão",
    description: "Costelinha de porco marinada na cachaça e ervas finas, dourada no ponto perfeito, servida com tutu de feijão aveludado, arroz branco, couve refogada e ovo caipira frito.",
    price: 36.0,
    category: "pratos-principais",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
  },
  {
    id: "prod-fm-3",
    tenantId: "tenant-fogao-de-minas",
    name: "Porção de Torresmo à Pururuca Crocante",
    description: "Porção de 300g de torresmo artesanal super crocante, pururucado com técnica tradicional e temperado na medida com sal e gotas de limão.",
    price: 24.0,
    category: "porcoes",
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-fm-4",
    tenantId: "tenant-fogao-de-minas",
    name: "Pudim de Leite Condensado Caseiro da Vovó",
    description: "Fatia caprichada de pudim de leite lisinho, cremoso e sem furinhos, banhado em calda dourada de caramelo aromático.",
    price: 12.0,
    category: "sobremesas",
    image: "https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },

  // 16. Pastel D'Ouro Crocante & Caldo de Cana (tenant-pastel-ouro)
  {
    id: "prod-po-1",
    tenantId: "tenant-pastel-ouro",
    name: "Pastel Especial de Carne Seca com Catupiry (30cm)",
    description: "Pastel gigante com massa crocante e sequinha, recheado de ponta a ponta com carne seca desfiada bem temperadinha na cebola roxa e Catupiry legítimo cremoso.",
    price: 19.9,
    category: "pasteis-especiais",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-po-queijo-extra", name: "Dobro de Queijo Muçarela Derretido", price: 3.5 },
      { id: "opt-po-vinagrete", name: "Vinagrete e Molho de Pimenta Especial (Grátis)", price: 0.0 },
    ],
  },
  {
    id: "prod-po-2",
    tenantId: "tenant-pastel-ouro",
    name: "Pastel de Palmito com Muçarela & Orégano (30cm)",
    description: "Massa crocante estalando recheada com palmito macio refogado no azeite, muçarela derretida e toque especial de orégano.",
    price: 17.5,
    category: "pasteis-salgados",
    image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
  },
  {
    id: "prod-po-3",
    tenantId: "tenant-pastel-ouro",
    name: "Pastel Doce de Nutella com Pedaços de Morango",
    description: "Pastel frito na hora com recheio quente de creme de avelã Nutella original e fatias de morango fresco, polvilhado com açúcar de confeiteiro.",
    price: 16.0,
    category: "pasteis-doces",
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-po-4",
    tenantId: "tenant-pastel-ouro",
    name: "Caldo de Cana Natural Geladinho 500ml",
    description: "Moído na hora de cana selecionada e higienizada, servido super gelado com opção de toque de limão taiti ou abacaxi.",
    price: 8.0,
    category: "bebidas",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },

  // 17. Crispy Chicken - Frango no Balde (tenant-frango-crocante)
  {
    id: "prod-cc-1",
    tenantId: "tenant-frango-crocante",
    name: "Balde Clássico de Tirinhas Crocantes (500g)",
    description: "Meio quilo de tiras de filé de peito de frango selecionadas, marinadas por 12 horas em tempero especial e empanadas em farinha ultra crocante. Acompanha 2 molhos especiais.",
    price: 36.9,
    category: "baldes",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-cc-molho-barbecue", name: "Molho Barbecue Defumado", price: 0.0 },
      { id: "opt-cc-molho-honey-mustard", name: "Molho Honey Mustard (Mostarda e Mel)", price: 0.0 },
      { id: "opt-cc-molho-alho-ervas", name: "Maionese Artesanal de Alho e Ervas", price: 0.0 },
      { id: "opt-cc-batata-combo", name: "Adicionar Batata Frita Grande", price: 12.0 },
    ],
  },
  {
    id: "prod-cc-2",
    tenantId: "tenant-frango-crocante",
    name: "Balde Família Mega Mix (1kg de Frango + Batata)",
    description: "O combo mais pedido da galera: 1kg dividido entre tirinhas crocantes e tulipas de frango empanadas + porção de batatas fritas douradas + 4 molhos à sua escolha.",
    price: 64.9,
    category: "baldes",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
  },
  {
    id: "prod-cc-3",
    tenantId: "tenant-frango-crocante",
    name: "Sanduíche Crispy Bacon Burger",
    description: "Pão brioche fofinho amanteigado, filé de frango empanado extra crocante, fatias de queijo cheddar derretido, tiras de bacon estalando, alface fresca e maionese especial.",
    price: 28.0,
    category: "sanduiches",
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-cc-4",
    tenantId: "tenant-frango-crocante",
    name: "Onion Rings Douradas (Anéis de Cebola)",
    description: "Porção de anéis de cebola selecionados empanados em massa crocante e sequinha, servidos com molho barbecue artesanal.",
    price: 18.0,
    category: "porcoes",
    image: "https://images.unsplash.com/photo-1639024471285-0afc3855f485?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },

  // 18. Creperia & Tapiocaria Paris (tenant-crepe-paris)
  {
    id: "prod-cp-1",
    tenantId: "tenant-crepe-paris",
    name: "Crepe Francês de Frango com Catupiry & Palmito",
    description: "Massa fininha e leve preparada na chapa francesa, recheada com peito de frango desfiado temperado, Catupiry original, pedacinhos de palmito e toque de orégano.",
    price: 24.9,
    category: "crepes-salgados",
    image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-cp-dobro-recheio", name: "Dobro de Recheio de Catupiry", price: 4.0 },
    ],
  },
  {
    id: "prod-cp-2",
    tenantId: "tenant-crepe-paris",
    name: "Crepe de Nutella Supreme com Morangos & Banana",
    description: "Massa leve de crepe recheada com farta camada de Nutella, fatias de morango fresco e banana fatiada, finalizada com castanhas tostadas e calda de chocolate.",
    price: 26.0,
    category: "crepes-doces",
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
  },
  {
    id: "prod-cp-3",
    tenantId: "tenant-crepe-paris",
    name: "Tapioca Nordestina de Carne Seca com Queijo Coalho",
    description: "Tapioca quentinha e macia na medida certa, recheada generosamente com carne seca desfiada na manteiga de garrafa e queijo coalho tostadinho na chapa.",
    price: 21.0,
    category: "tapiocas",
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-cp-4",
    tenantId: "tenant-crepe-paris",
    name: "Waffle Americano com Manteiga & Mel de Flor de Laranjeira",
    description: "Waffle crocante por fora e aerado por dentro, servido quentinho com manteiga de primeira e mel puro.",
    price: 16.5,
    category: "sobremesas",
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },

  // 19. Padaria & Empório Pão Dourado (tenant-padaria-pao-dourado)
  {
    id: "prod-pd-1",
    tenantId: "tenant-padaria-pao-dourado",
    name: "Croissant Francês Amanteigado com Presunto & Queijo",
    description: "Croissant artesanal folhado de massa dourada e amanteigada, recheado com presunto fatiado fininho e queijo prato derretido, aquecido na hora.",
    price: 15.9,
    category: "folhados-paes",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-pd-cafe-combo", name: "Combo com Café com Leite 300ml", price: 5.5 },
    ],
  },
  {
    id: "prod-pd-2",
    tenantId: "tenant-padaria-pao-dourado",
    name: "Sanduíche Misto Quente Especial no Pão da Casa",
    description: "Pão artesanal tostado na manteiga de fazenda, fatias generosas de queijo muçarela derretido, presunto royale e pitada de orégano.",
    price: 12.5,
    category: "lanches",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
  },
  {
    id: "prod-pd-3",
    tenantId: "tenant-padaria-pao-dourado",
    name: "Pão de Queijo Mineiro Tradicional (Porção com 6)",
    description: "6 unidades de pães de queijo preparados com queijo canastra meia cura legítimo e polvilho doce, assados na hora, quentinhos e puxa-puxa.",
    price: 14.0,
    category: "salgados",
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-pd-4",
    tenantId: "tenant-padaria-pao-dourado",
    name: "Cappuccino Cremoso com Canela e Raspas de Chocolate",
    description: "Dose de café espresso encorpado, leite vaporizado aveludado, cacau em pó 50% e pitada suave de canela.",
    price: 9.5,
    category: "cafes-bebidas",
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },

  // 20. Aloha Hawaiian Poke & Saladas (tenant-poke-tropical)
  {
    id: "prod-pt-1",
    tenantId: "tenant-poke-tropical",
    name: "Poke Havaiano Clássico de Salmão Fresco",
    description: "Base de arroz japonês shari morno, cubos generosos de salmão fresco marinados em molho shoyu especial e óleo de gergelim torrado, cream cheese, manga em cubos, edamame, pepino japonês sunomono, chips de batata doce e gergelim bicolor.",
    price: 44.9,
    category: "pokes",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 0,
    options: [
      { id: "opt-pt-molho-tarê", name: "Molho Tarê Especial", price: 0.0 },
      { id: "opt-pt-molho-wasabi", name: "Maionese Spicy de Wasabi", price: 0.0 },
      { id: "opt-pt-extra-salmao", name: "Porção Extra de Salmão em Cubos (80g)", price: 12.0 },
      { id: "opt-pt-abacate", name: "Abacate / Avocado Fatiado", price: 4.5 },
    ],
  },
  {
    id: "prod-pt-2",
    tenantId: "tenant-poke-tropical",
    name: "Poke Tropical de Atum Selado & Frutas",
    description: "Cubos de atum fresco selados em crosta de gergelim, arroz shari, abacaxi grelhado, lâminas de rabanete, cenoura ralada, cebolinha fresca e molho ponzu cítrico refrescante.",
    price: 42.0,
    category: "pokes",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 1,
  },
  {
    id: "prod-pt-3",
    tenantId: "tenant-poke-tropical",
    name: "Wrap Integral de Frango Grelhado com Ricota & Ervas",
    description: "Pão folha integral recheado com peito de frango em tiras grelhado, pasta leve de ricota com ervas finas, tomate seco, folhas verdes crocantes e azeite extravirgem.",
    price: 24.5,
    category: "wraps-saladas",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 2,
  },
  {
    id: "prod-pt-4",
    tenantId: "tenant-poke-tropical",
    name: "Suco Natural Detox Verde Prensado 400ml",
    description: "Couve fresca, maçã verde, limão siciliano, pepino e água de coco natural batidos na hora sem adição de açúcar.",
    price: 11.0,
    category: "bebidas",
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80",
    available: true,
    position: 3,
  },
];

// =========================================================================
// STORIES ATIVOS PARA TODAS AS 9 NOVAS LOJAS DEMONSTRATIVAS
// =========================================================================
export const extraStories: StoreStory[] = [
  // 12. Bella Pasta
  {
    id: "story-bp-1",
    tenantId: "tenant-cantina-italiana",
    mediaUrl: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🍝 Festival da Parmegiana! Filé suculento com molho artesanal de tomate fresco e muita muçarela.",
    createdAt: Date.now() - 2 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-bp-2",
    tenantId: "tenant-cantina-italiana",
    mediaUrl: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🔥 Lasanhas saindo quentinhas do forno a lenha! Peça agora e receba em casa.",
    createdAt: Date.now() - 1 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },

  // 13. Dogão Prensado
  {
    id: "story-dp-1",
    tenantId: "tenant-dogao-prensado",
    mediaUrl: "https://images.unsplash.com/photo-1619740455993-9e612b1af08a?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🌭 Dogão prensado com muito purê caseiro e bacon! O lanche perfeito da sua noite.",
    createdAt: Date.now() - 3 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-dp-2",
    tenantId: "tenant-dogao-prensado",
    mediaUrl: "https://images.unsplash.com/photo-1627054234553-9f89972b9472?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🍟 Batata frita crocante com cheddar cremoso e farofa de bacon sequinha!",
    createdAt: Date.now() - 1 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },

  // 14. Taco Loco
  {
    id: "story-tl-1",
    tenantId: "tenant-taco-loco",
    mediaUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🌮 Terça de Tacos! Nachos crocantes com queijo cheddar quente e guacamole cremosa.",
    createdAt: Date.now() - 4 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-tl-2",
    tenantId: "tenant-taco-loco",
    mediaUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🌯 Burrito gigante bem recheado com queijo derretido e carnes temperadas!",
    createdAt: Date.now() - 2 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },

  // 15. Fogão de Minas
  {
    id: "story-fm-1",
    tenantId: "tenant-fogao-de-minas",
    mediaUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🍲 Feijoada completa da casa com torresmo à pururuca super estalando! Peça para o seu almoço.",
    createdAt: Date.now() - 2 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-fm-2",
    tenantId: "tenant-fogao-de-minas",
    mediaUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🥩 Costelinha suína macia douradinha com mandioca na manteiga de garrafa!",
    createdAt: Date.now() - 1 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },

  // 16. Pastel D'Ouro
  {
    id: "story-po-1",
    tenantId: "tenant-pastel-ouro",
    mediaUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🥟 Pastéis de 30cm fritos na hora com massa dourada e sequinha + caldo de cana geladinho!",
    createdAt: Date.now() - 3 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-po-2",
    tenantId: "tenant-pastel-ouro",
    mediaUrl: "https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🥟 Pastel doce de banana com canela e muito doce de leite quentinho derretendo!",
    createdAt: Date.now() - 1 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },

  // 17. Crispy Chicken
  {
    id: "story-cc-1",
    tenantId: "tenant-frango-crocante",
    mediaUrl: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🍗 Baldes de frango ultra crocantes por fora e macios por dentro com molhos especiais!",
    createdAt: Date.now() - 1 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-cc-2",
    tenantId: "tenant-frango-crocante",
    mediaUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🔥 Tiras crocantes de frango empanado com batatas rústicas e anéis de cebola!",
    createdAt: Date.now() - 2 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },

  // 18. Creperia Paris
  {
    id: "story-cp-1",
    tenantId: "tenant-crepe-paris",
    mediaUrl: "https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🥞 Crepes fininhos franceses recheados com morangos frescos e Nutella cremosa!",
    createdAt: Date.now() - 2 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-cp-2",
    tenantId: "tenant-crepe-paris",
    mediaUrl: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🧀 Tapioca recheada com carne seca e queijo coalho tostado na manteiga de garrafa!",
    createdAt: Date.now() - 1 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },

  // 19. Padaria Pão Dourado
  {
    id: "story-pd-1",
    tenantId: "tenant-padaria-pao-dourado",
    mediaUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🥐 Croissants folhados quentinhos e cafés especiais para transformar o seu dia!",
    createdAt: Date.now() - 4 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-pd-2",
    tenantId: "tenant-padaria-pao-dourado",
    mediaUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🥖 Pão artesanal de fermentação natural com casca crocante e miolo aveludado!",
    createdAt: Date.now() - 2 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },

  // 20. Aloha Poke
  {
    id: "story-pt-1",
    tenantId: "tenant-poke-tropical",
    mediaUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🥗 Pokes havaianos com salmão fresco marinado, manga, edamame e chips crocantes!",
    createdAt: Date.now() - 1 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
  {
    id: "story-pt-2",
    tenantId: "tenant-poke-tropical",
    mediaUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1080&q=80",
    mediaType: "image",
    caption: "🥑 Wrap saudável com mix de folhas, frango grelhado e molho especial refrescante!",
    createdAt: Date.now() - 2 * 3600000,
    expiresAt: Date.now() + 48 * 3600000,
  },
];

// =========================================================================
// GRUPOS DE ADICIONAIS DAS NOVAS LOJAS
// =========================================================================
export const extraAddonGroups: AddonGroup[] = [
  // 12. Bella Pasta
  {
    id: "addon-bp-molhos",
    tenantId: "tenant-cantina-italiana",
    name: "Acompanhamentos & Molhos Especiais",
    description: "Escolha queijos e complementos para a sua massa",
    minSelection: 0,
    maxSelection: 3,
    required: false,
    items: [
      { id: "item-bp-parmesao", name: "Parmesão Ralado na Hora (50g)", price: 4.5, available: true },
      { id: "item-bp-alho-oleo", name: "Pão de Alho Artesanal da Cantina", price: 6.0, available: true },
      { id: "item-bp-molho-pesto", name: "Molho Pesto de Manjericão e Nozes", price: 5.0, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 14 * 86400000,
  },

  // 13. Dogão Prensado
  {
    id: "addon-dp-adicionais",
    tenantId: "tenant-dogao-prensado",
    name: "Turbine o seu Dogão",
    description: "Adicione mais recheio ao seu cachorro-quente",
    minSelection: 0,
    maxSelection: 4,
    required: false,
    items: [
      { id: "item-dp-bacon", name: "Farofa de Bacon Crocante", price: 3.5, available: true },
      { id: "item-dp-catupiry", name: "Catupiry Original no Pão", price: 3.5, available: true },
      { id: "item-dp-cheddar", name: "Calda de Cheddar Cremoso", price: 3.5, available: true },
      { id: "item-dp-pure", name: "Dobro de Purê de Batata da Casa", price: 2.5, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 12 * 86400000,
  },

  // 14. Taco Loco
  {
    id: "addon-tl-salsas",
    tenantId: "tenant-taco-loco",
    name: "Salsas & Molhos Mexicanos",
    description: "Escolha os molhos típicos para os seus tacos e nachos",
    minSelection: 0,
    maxSelection: 3,
    required: false,
    items: [
      { id: "item-tl-guacamole", name: "Guacamole Fresca com Coentro e Limão", price: 6.0, available: true },
      { id: "item-tl-sourcream", name: "Sour Cream Especial", price: 4.5, available: true },
      { id: "item-tl-pico", name: "Pico de Gallo Artesanal", price: 3.5, available: true },
      { id: "item-tl-jalapeno", name: "Pimentas Jalapeños Fatiadas", price: 3.0, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 11 * 86400000,
  },

  // 15. Fogão de Minas
  {
    id: "addon-fm-acompanhamentos",
    tenantId: "tenant-fogao-de-minas",
    name: "Acompanhamentos Mineiros Extras",
    description: "Turbine sua feijoada e pratos típicos",
    minSelection: 0,
    maxSelection: 4,
    required: false,
    items: [
      { id: "item-fm-torresmo", name: "Torresmo à Pururuca Extra Estalando (100g)", price: 6.5, available: true },
      { id: "item-fm-couve", name: "Couve Manteiga Refogada no Alho", price: 4.0, available: true },
      { id: "item-fm-tutu", name: "Tutu de Feijão Cremoso com Bacon", price: 5.5, available: true },
      { id: "item-fm-ovo", name: "Ovo Caipira Frito na Hora", price: 2.5, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 16 * 86400000,
  },

  // 16. Pastel D'Ouro
  {
    id: "addon-po-extras",
    tenantId: "tenant-pastel-ouro",
    name: "Recheios Extras & Molhos da Feira",
    description: "Adicione mais recheio ou molhos ao seu pastel",
    minSelection: 0,
    maxSelection: 3,
    required: false,
    items: [
      { id: "item-po-queijo", name: "Queijo Muçarela Extra Derretido", price: 4.0, available: true },
      { id: "item-po-catupiry", name: "Catupiry Original Farto", price: 4.0, available: true },
      { id: "item-po-bacon", name: "Bacon Crocante em Cubinhos", price: 3.5, available: true },
      { id: "item-po-vinagrete", name: "Potinho de Vinagrete Especial da Feira", price: 2.5, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 9 * 86400000,
  },

  // 17. Crispy Chicken
  {
    id: "addon-cc-dips",
    tenantId: "tenant-frango-crocante",
    name: "Molhos & Dips para o Balde",
    description: "Molhos especiais para mergulhar as tirinhas de frango crocante",
    minSelection: 0,
    maxSelection: 4,
    required: false,
    items: [
      { id: "item-cc-bbq", name: "Barbecue Defumado Americano", price: 3.0, available: true },
      { id: "item-cc-honey", name: "Honey Mustard (Mostarda e Mel)", price: 3.0, available: true },
      { id: "item-cc-garlic", name: "Maionese Especial de Alho e Ervas", price: 3.0, available: true },
      { id: "item-cc-spicy", name: "Molho Hot Pepper Picante", price: 3.0, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 8 * 86400000,
  },

  // 18. Creperia Paris
  {
    id: "addon-cp-recheios",
    tenantId: "tenant-crepe-paris",
    name: "Acompanhamentos Gourmet para Crepes",
    description: "Personalize seus crepes franceses e tapiocas",
    minSelection: 0,
    maxSelection: 4,
    required: false,
    items: [
      { id: "item-cp-sorvete", name: "Bola de Sorvete de Creme Artesanal", price: 5.0, available: true },
      { id: "item-cp-morango", name: "Morangos Frescos Fatiados", price: 4.5, available: true },
      { id: "item-cp-nutella", name: "Dose Extra de Nutella Pura Original", price: 5.0, available: true },
      { id: "item-cp-coalho", name: "Queijo Coalho Grelhado em Tiras", price: 4.5, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 6 * 86400000,
  },

  // 19. Padaria Pão Dourado
  {
    id: "addon-pd-cafe",
    tenantId: "tenant-padaria-pao-dourado",
    name: "Acompanhamentos para Pães & Cafés",
    description: "Complementos artesanais para o seu café da manhã ou lanche",
    minSelection: 0,
    maxSelection: 3,
    required: false,
    items: [
      { id: "item-pd-manteiga", name: "Manteiga Aviação Derretida no Pote", price: 3.0, available: true },
      { id: "item-pd-geleia", name: "Geleia Artesanal de Frutas Vermelhas", price: 4.0, available: true },
      { id: "item-pd-requeijao", name: "Requeijão Cremoso de Fazenda", price: 3.5, available: true },
      { id: "item-pd-chantilly", name: "Chantilly Fresco Batido na Hora", price: 3.0, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 25 * 86400000,
  },

  // 20. Aloha Poke
  {
    id: "addon-pt-toppings",
    tenantId: "tenant-poke-tropical",
    name: "Toppings & Crocantes para o Poke",
    description: "Personalize a textura do seu bowl",
    minSelection: 0,
    maxSelection: 4,
    required: false,
    items: [
      { id: "item-pt-chips", name: "Chips de Batata Doce Crocantes", price: 3.5, available: true },
      { id: "item-pt-nori", name: "Tirinhas Crocantes de Alga Nori", price: 3.0, available: true },
      { id: "item-pt-castanha", name: "Castanha de Caju Tostada e Picada", price: 4.0, available: true },
      { id: "item-pt-creamcheese", name: "Cream Cheese Philadelphia em Gotas", price: 4.0, available: true },
    ],
    position: 1,
    createdAt: Date.now() - 7 * 86400000,
  },
];
