name = "top-food-delivery"
compatibility_date = "2024-09-01"
main = "src/worker.ts"

[vars]
PLATFORM_NAME = "Top Food Multi-tenant"
ENVIRONMENT = "production"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "delivery_db"
database_id = "f9d56732-ee68-4120-99c2-2bad2de74d8b"
migrations_dir = "migrations"

# Cloudflare KV Namespace Binding (para cache e configurações rápidas de tenant)
[[kv_namespaces]]
binding = "STORE_KV"
id = "958f3736bcc74c488fe31b6a3855263f"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
